@echo off
REM ============================================================================
REM  FocusLock - install the always-on background service (Cold Turkey style)
REM
REM  This makes the enforcer run on its own, without you keeping the app open:
REM
REM    1. Builds the project (via setup.bat).
REM    2. Writes a tiny hidden watchdog script.
REM    3. Registers two Scheduled Tasks (run only while you are logged on):
REM         - "FocusLock Service Startup"  : starts the service at logon.
REM         - "FocusLock Service Watchdog" : every 1 minute, restarts the
REM                                          service within ~60s if it ever dies.
REM    4. Starts the service now.
REM
REM  No admin rights required - the tasks run in your own user session.
REM  To remove all of this, run uninstall-background.bat.
REM ============================================================================

setlocal
cd /d "%~dp0"

set "VBS=%~dp0.focuslock-watchdog.vbs"
set "TASK_WATCH=FocusLock Service Watchdog"
set "TASK_LOGON=FocusLock Service Startup"

echo(
echo   FocusLock - background service install
echo   ======================================
echo(

REM --- 1. Build (installs deps + compiles). setup.bat is visible on purpose. --
call "%~dp0setup.bat"
if errorlevel 1 (
    echo   [X] Build failed - fix the errors above and re-run.
    pause
    exit /b 1
)

if not exist "%~dp0packages\service\dist\index.js" (
    echo   [X] The service build is missing (packages\service\dist\index.js).
    pause
    exit /b 1
)

REM --- 2. Write the hidden watchdog helper ------------------------------------
REM  It asks the service /health; if it does not answer, it relaunches the
REM  service with NO console window. Uses MSXML2.XMLHTTP so there are no pipes
REM  or temp files to escape. wscript.exe runs it with no visible window.
echo   Writing watchdog helper...
>"%VBS%"  echo ' FocusLock service watchdog - auto-generated by install-background.bat. Do not edit.
>>"%VBS%" echo Option Explicit
>>"%VBS%" echo Dim fso, sh, root, svc
>>"%VBS%" echo Set fso = CreateObject("Scripting.FileSystemObject")
>>"%VBS%" echo Set sh  = CreateObject("WScript.Shell")
>>"%VBS%" echo root = fso.GetParentFolderName(WScript.ScriptFullName)
>>"%VBS%" echo svc  = root ^& "\packages\service\dist\index.js"
>>"%VBS%" echo If Not fso.FileExists(svc) Then WScript.Quit 0
>>"%VBS%" echo Dim up : up = False
>>"%VBS%" echo On Error Resume Next
>>"%VBS%" echo Dim http : Set http = CreateObject("MSXML2.XMLHTTP")
>>"%VBS%" echo http.Open "GET", "http://127.0.0.1:47615/health", False
>>"%VBS%" echo http.Send
>>"%VBS%" echo If Err.Number = 0 And http.Status = 200 Then up = True
>>"%VBS%" echo On Error GoTo 0
>>"%VBS%" echo If Not up Then
>>"%VBS%" echo   sh.CurrentDirectory = root
>>"%VBS%" echo   sh.Run "node """ ^& svc ^& """", 0, False
>>"%VBS%" echo End If

REM --- 3. Register the scheduled tasks (idempotent) --------------------------
echo   Registering scheduled tasks...
schtasks /Delete /TN "%TASK_WATCH%" /F >nul 2>nul
schtasks /Delete /TN "%TASK_LOGON%" /F >nul 2>nul
schtasks /Create /TN "%TASK_WATCH%" /TR "wscript.exe \"%VBS%\"" /SC MINUTE /MO 1 /F
if errorlevel 1 (
    echo   [X] Could not create the watchdog task.
    pause
    exit /b 1
)
schtasks /Create /TN "%TASK_LOGON%" /TR "wscript.exe \"%VBS%\"" /SC ONLOGON /F
if errorlevel 1 (
    echo   [X] Could not create the startup task.
    pause
    exit /b 1
)

REM --- 4. Start it now --------------------------------------------------------
echo   Starting the service now...
wscript "%VBS%"

echo(
echo   Done. FocusLock's service is now always-on:
echo     - starts automatically when you log in, and
echo     - is restarted within ~1 minute if it ever stops.
echo(
echo   Next: open chrome://extensions, and click the reload (circular arrow) on
echo   FocusLock (or Load unpacked -^> apps\extension) so the new code loads.
echo(
pause
endlocal
exit /b 0
